name: VCD-net

dependencies:
  - python=3.7
  - imageio==2.4.1
  - scipy==1.2.0
  - scikit-image==0.14.1
  - tensorflow-gpu==1.14.0
  - numpy=1.15.4
  - pip
  - pip:
    - easydict==1.9

channels:
  - anaconda
  - conda-forge
  - simpleitk
